[dev]
  command = "npm run dev"
  framwork = "#custom"
  port = 8888
  publish = "dist"

  [build]
    functions="functions"

[[redirects]]
    to="/.netlify/functions/:splat"
    from="/*"
    status=200 