[dev]
  command = "npm run dev"
  framwork = "#custom"
  targetPort = 3000
  port = 8888
  publish = "dist"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[build]
  functions="functions"

[[redirects]]
    to="/.netlify/functions/:splat"
    from="/*"
    status=200 

[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "https://cattown.netlify.app"